### ISSUE TITLE
This is awesome!!!

### ISSUE THREAD

**Issue by marbetschar** [JotaMelo/jSpringBoard#2]
Any chance on abstracting the "apps and folders" part into a framework so this can be used within 3rd party apps?

So something like this gets possible:

<img width="413" alt="bildschirmfoto 2018-02-14 um 21 18 37" src="https://user-images.githubusercontent.com/392542/36225957-acb0388e-11cc-11e8-886b-93d3f67f1cfa.png">

**Comment by JotaMelo** [comment]
Hey, glad you liked it!!
That's an interesting idea. Unfortunately I can't work on it anymore but feel free to do whatever you want with the code.
